### ISSUE TITLE
Tracker web UI: recent items displayed is off by one

### ISSUE THREAD

**Issue by chfoo** [ArchiveTeam/terroroftinytown#29]
The number of rows displayed in recent items table for the tracker's homepage is off by one.

**Comment by chriscoffee** [comment]
Quickly checked this locally and removing the `-1` from fixes this.

https://github.com/ArchiveTeam/terroroftinytown/blob/127ea7c7fe3f79ed728cfce9f1ef45fd2b3696a0/terroroftinytown/tracker/static/stats.js#L142
