### ISSUE TITLE
Distinguish redirects from non-redirects by Location header, not just status code

### ISSUE THREAD

**Issue by JesseWeinstein** [ArchiveTeam/terroroftinytown#47]
I've seen quite a few shortners that seem to return 301 for both existing AND non-existing shortcodes.

I suggest that an additional project setting be added, called `location_regex`, which if non-empty, would be used after the redirect status code as a way to handle such shortners. If the `location_regex` matched the `Location:` header, the short code would be considered a non-redirect, even though it had a redirect status code.

**Comment by chfoo** [comment]
Closing because it was implemented and merged in the pull request already
