### ISSUE TITLE
Fix menus on project-specific Results & Error Reports

### ISSUE THREAD

**Issue by JesseWeinstein** [ArchiveTeam/terroroftinytown#50]
I think those pages should have the project-specific menu, along with a link to the global Results (or Error Reports, respectively).

Also, I'd probably blow away the redundant "Overview" menu item.

(And maybe add links from the global results and error reports project column to the project-specific equivalent)

**Comment by chfoo** [comment]
Sounds good.

**Comment by chfoo** [comment]
Closing because it was implemented and merged in the pull request already
