### ISSUE TITLE
Support HTTPS

### ISSUE THREAD

**Issue by chfoo** [ArchiveTeam/terroroftinytown#55]
Requests to the tracker should support an HTTPS option. For example, the tracker runs as HTTPS on tracker.archiveteam.org:1338 so the code should be able to handle that port 1338 is HTTPS.

**Comment by chriscoffee** [comment]
Some discussion in IRC related to this:

>Keep in mind that the warrior VM is absurdly out-of-date and has an ancient OpenSSL version...I think it doesn't support TLS 1.1 or 1.2. Not sure if that's relevant for the URLTeam tracker specifically, but it's definitely worth keeping in mind when working with anything related to the warrior and HTTPS.

Worth doing some checks/tests during solving the ticket.

**Comment by chfoo** [comment]
Closing because latest changes seem to be working fine
